using UnityEngine;
using IK.Settings;

namespace IK.App {
    /// <summary>
    /// dev.6 background music. The screenpack's own BGM files (system.def `[Music]`
    /// title/select/vs/victory/continue.bgm, stage `bgmusic`) are not in the repository, so
    /// the game ships original tracks generated by tools/music/compose.py
    /// (Resources/music/*.ogg, MIT like our code). One track per screen like Ikemen's motif
    /// music; a fight picks one of the fight tracks from the stage name so a stage always has
    /// the same music. Volume = Options → BGM volume (master is AudioListener.volume).
    /// Music keeps playing when the next screen asks for the same looping track.
    /// </summary>
    public class MusicPlayer : MonoBehaviour {
        public static readonly string[] FightTracks = { "fight1", "fight2", "fight3" };
        AudioSource src;
        public string Playing { get; private set; } = "";
        /// <summary>The track that is playing or about to play once the fade-out ends.</summary>
        public string Current => pending ?? Playing;
        float fade = 1f;
        string pending;
        bool pendingLoop;

        void Awake() {
            src = gameObject.AddComponent<AudioSource>();
            src.playOnAwake = false;
            src.spatialBlend = 0f;
            src.priority = 0;
        }

        /// <summary>The fight track of a stage (stable per stage def).</summary>
        public static string ForStage(string stageDef) {
            int h = 0;
            foreach (char c in (stageDef ?? "").ToLowerInvariant()) h = h * 31 + c;
            return FightTracks[(h & 0x7fffffff) % FightTracks.Length];
        }

        /// <summary>Starts a track ("" = silence). A looping track already playing continues.</summary>
        public void Play(string name, bool loop = true) {
            name = name ?? "";
            if (name == Playing && src.isPlaying && src.loop) return;
            if (name.Length == 0) { pending = null; Playing = ""; fade = -1f; return; }
            pending = name; pendingLoop = loop;
            if (!src.isPlaying) Swap();
            else fade = -1f;                   // fade the old one out first
        }

        void Swap() {
            var clip = Resources.Load<AudioClip>("music/" + pending);
            Playing = pending;
            pending = null;
            src.Stop();
            if (clip == null) { Debug.LogWarning("[IK] music not found: " + Playing); return; }
            src.clip = clip;
            src.loop = pendingLoop;
            fade = 0f;
            src.volume = 0f;
            src.Play();
        }

        void Update() {
            float target = SettingsStore.Current != null ? SettingsStore.Current.bgmVolume / 100f : 0.75f;
            if (fade < 0f) {
                src.volume = Mathf.MoveTowards(src.volume, 0f, Time.unscaledDeltaTime * 2f);
                if (src.volume <= 0.001f) {
                    src.Stop();
                    if (pending != null) Swap(); else fade = 1f;
                }
                return;
            }
            if (fade < 1f) fade = Mathf.Min(1f, fade + Time.unscaledDeltaTime * 2f);
            src.volume = target * fade;
        }
    }
}
